import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { brands, blogs, footerGroups, jewelleryCategories, jewelleryImage, news } from '@/lib/data';
import { MediaFeature } from '@/components/MediaFeature';

export function SectionHeading({ kicker, title, note, dark = false }: { kicker: string; title: string; note?: string; dark?: boolean }) { return <div className={`section-heading ${dark ? 'on-dark' : ''}`}><span className="eyebrow">{kicker}</span><h2>{title}</h2>{note && <p>{note}</p>}</div>; }

export function MuhuratSection() { return <section className="muhurat section-wrap"><div className="muhurat-image"><Image src={jewelleryImage('photo-1617038260897-41a1f14a8ca0')} alt="Bridal jewellery inspired by Indian wedding traditions" fill sizes="(max-width: 760px) 100vw, 52vw"/><span className="image-label">THE WEDDING EDIT · 2024</span></div><div className="muhurat-copy"><span className="eyebrow">A WEDDING COLLECTION</span><h2>Traditions,<br/><i>made yours.</i></h2><p>Inspired by India’s many customs and traditions, Muhurat brings together bridal jewellery as unique as the stories behind it. A collection for the beginning of everything.</p><Link href="/muhurat" className="button button-wine">EXPLORE MUHURAT <ArrowUpRight size={15}/></Link><div className="muhurat-ornament">M</div></div></section>; }

export function BrandSection() { return <section className="brand-section section-wrap" id="brands"><SectionHeading kicker="A FAMILY OF EXPRESSIONS" title="BRANDS FAMILY" note="Many traditions. One promise of exceptional craft."/><div className="brand-grid">{brands.map((brand, i) => <Link href="/brands" className={`brand-card brand-card-${i}`} key={brand.name}><div className="brand-photo"><Image src={jewelleryImage(brand.image)} alt={`${brand.name} jewellery collection`} fill sizes="(max-width: 760px) 75vw, 28vw"/></div><div className="brand-card-copy"><span className="brand-index">0{i + 1}</span><h3>{brand.name}</h3><p>{brand.detail}</p><span className="brand-explore">EXPLORE <ArrowUpRight size={15}/></span></div></Link>)}</div><Link className="text-link centered-link" href="/brands">MEET THE FAMILY <span>↗</span></Link></section>; }

export function CategorySection() { return <section className="category-section section-wrap" id="collections"><SectionHeading kicker="FIND YOUR FOREVER PIECE" title="JEWELLERY, WITH A STORY"/><div className="category-grid">{jewelleryCategories.map((item, i) => <Link href="/jewellery" className={`category-card category-${i}`} key={item.title}><div className="category-photo"><Image src={jewelleryImage(item.image)} alt={`${item.title} jewellery`} fill sizes="(max-width: 760px) 50vw, 34vw"/></div><div className="category-title"><h3>{item.title}</h3><span><ArrowUpRight size={17}/></span></div></Link>)}</div></section>; }

export function AboutSection() { return <section className="about-section section-wrap" id="about"><div className="about-photo"><Image src="/images/leadership/chairman-wide.webp" alt="T. S. Kalyanaraman, chairman of Kalyan Jewellers" fill sizes="(max-width: 760px) 100vw, 50vw"/><span>THRISSUR, KERALA · OUR BEGINNING</span></div><div className="about-copy"><span className="eyebrow">A LEGACY THAT SHINES</span><h2>Rooted in<br/><i>tradition.</i><br/>Made for today.</h2><p>Our story began in Thrissur, Kerala, with a belief that jewellery should be as genuine as the moments it celebrates. Decades on, that promise continues in every piece and every relationship.</p><Link href="/about" className="text-link">OUR STORY <span>↗</span></Link></div></section>; }

export function LeadershipSection() { const people = [{ name: 'T. S. Kalyanaraman', role: 'CHAIRMAN & MANAGING DIRECTOR', image: '/images/leadership/chairman-wide.webp' }, { name: 'Rajesh Kalyanaraman', role: 'EXECUTIVE DIRECTOR', image: '/images/leadership/rajesh-kalyan.webp' }, { name: 'Ramesh Kalyanaraman', role: 'EXECUTIVE DIRECTOR', image: '/images/leadership/ramesh-kalyan.webp' }]; return <section className="leadership-section section-wrap" id="leadership"><div className="leadership-intro"><span className="eyebrow">THE PEOPLE BEHIND THE PROMISE</span><h2>A vision carried<br/><i>forward.</i></h2><blockquote>“Trust is built one relationship, one promise, and one piece of jewellery at a time.”</blockquote><span className="quote-credit">— T. S. KALYANARAMAN</span></div><div className="leaders">{people.map((person, i) => <article className="leader-card" key={person.name}><div className="leader-photo"><Image src={person.image} alt={person.name} fill sizes="(max-width: 760px) 70vw, 22vw"/></div><span className="eyebrow">{person.role}</span><h3>{person.name}</h3><span className="leader-number">0{i + 1}</span></article>)}</div></section>; }

export function NewsSection() { return <section className="news-section section-wrap" id="news"><div className="section-row"><SectionHeading kicker="THE LATEST FROM KALYAN" title="KALYAN NEWS"/><Link className="text-link" href="/news">ALL NEWS <span>↗</span></Link></div><div className="news-grid">{news.map((item, i) => <article className="news-card" key={item.title}><Link className="news-image" href={item.href}><Image src={jewelleryImage(item.image)} alt="Kalyan Jewellers showroom" fill sizes="(max-width: 760px) 90vw, 45vw"/><span>0{i + 1}</span></Link><div className="news-copy"><span className="eyebrow">{item.date} · COMPANY NEWS</span><h3>{item.title}</h3><p>{item.excerpt}</p><Link href={item.href} className="text-link">READ THE STORY <span>↗</span></Link></div></article>)}</div></section>; }

export function BlogSection() { return <section className="blog-section section-wrap" id="journal"><div className="section-row"><SectionHeading kicker="NOTES ON THE MOMENTS THAT MATTER" title="THE JOURNAL"/><Link className="text-link" href="/blog">ALL STORIES <span>↗</span></Link></div><div className="blog-grid">{blogs.map((item) => <article className="blog-card" key={item.title}><Link className="blog-image" href="/blog"><Image src={jewelleryImage(item.image)} alt="Jewellery inspiration" fill sizes="(max-width: 760px) 85vw, 31vw"/><span>{item.category}</span></Link><div className="blog-copy"><span className="eyebrow">{item.date}</span><h3>{item.title}</h3><p>{item.excerpt}</p><Link className="text-link" href="/blog">READ MORE <span>↗</span></Link></div></article>)}</div></section>; }

export function MediaSection() { return <section className="media-section"><div className="section-wrap"><div className="section-row"><SectionHeading kicker="A CLOSER LOOK" title="MOMENTS IN THE MAKING" dark/><Link className="text-link light-link" href="/media">EXPLORE MEDIA <span>↗</span></Link></div><MediaFeature/></div></section>; }

export function GiftSection() { return <section className="gift-section section-wrap" id="gift-card"><div className="gift-copy"><span className="eyebrow">A THOUGHTFUL WAY TO SAY IT</span><h2>Give them<br/><i>something golden.</i></h2><p>For every celebration, a gift chosen with care. Share the joy of choosing with a Kalyan gift card.</p><Link className="button button-wine" href="/contact">DISCOVER GIFT CARDS <ArrowUpRight size={15}/></Link></div><div className="gift-image"><Image src="/images/campaign/gift-card.webp" alt="Kalyan Jewellers gift card" fill sizes="(max-width: 760px) 90vw, 42vw"/></div></section>; }

export function Footer() { return <footer className="footer"><div className="footer-main"><Link href="/" className="footer-logo" aria-label="Kalyan Jewellers home"><span className="logo-mark">K</span><span>KALYAN<small>JEWELLERS</small></span></Link><div className="footer-groups">{footerGroups.map((group) => <div className="footer-group" key={group.title}><h3>{group.title}</h3>{group.links.map(([label, href]) => <Link href={href} key={label}>{label}</Link>)}</div>)}</div><div className="footer-contact"><span className="eyebrow">WE’RE HERE TO HELP</span><a href="tel:1800-425-7333">1800 425 7333</a><a href="mailto:customercare@kalyanjewellers.net">customercare@kalyanjewellers.net</a><span>INDIA · UAE · QATAR · OMAN · KUWAIT</span></div></div><div className="footer-bottom"><span>© 2024 KALYAN JEWELLERS. ALL RIGHTS RESERVED.</span><div><Link href="/contact">PRIVACY</Link><Link href="/contact">TERMS</Link><Link href="/contact">CONTACT</Link></div><a className="back-top" href="#top" aria-label="Back to top"><ArrowUpRight size={17}/></a></div></footer>; }
